name: Solid Rock Church
favicon: null
layout_spectrum: 0.8815
typography_spectrum: 0.64242
title: Solid Rock Church
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#4f6d95'
    - '#354654'
    - '#9bbcd9'
  brandStrength: 0.019286784809082747
  lightness: 0.67048145737499
  saturation: 0.6008902755565941
  rhythmicContrast: 0.9761160262860358
purpose: []
